#!/usr/bin/env ruby

ONE_LOCATION=ENV["ONE_LOCATION"] if !defined?(ONE_LOCATION)

if !ONE_LOCATION
    RUBY_LIB_LOCATION="/usr/lib/one/ruby" if !defined?(RUBY_LIB_LOCATION)
else
    RUBY_LIB_LOCATION=ONE_LOCATION+"/lib/ruby" if !defined?(RUBY_LIB_LOCATION)
end

$: << RUBY_LIB_LOCATION
$: << File.dirname(__FILE__) + '/../..'

require 'scripts_common'
require 'rubygems'
require "#{File.dirname(__FILE__)}/ovz_common"

ENV['LANG']='C'

vm_id = ARGV[0]
snapshot_id = ARGV[1]

read_shell_exports(File.join(File.dirname($0), "ovzrc"))

vm_conf = read_ovz_config(File.join(ENV["VZ_CONF_DIR"], "#{vm_id}.conf"))
dirname = vm_conf["VE_PRIVATE"]

$sudo    = ENV["SUDO"]
$vzctl   = ENV["VZCTL"]

output = `#{$sudo} #{$vzctl} snapshot #{vm_id}`

code = $?.exitstatus

if code == 0
	/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/ =~ output
	uuid = Regexp.last_match[0]

	user  = File.stat("#{dirname}").uid
	group = File.stat("#{dirname}").gid
	OpenNebula.exec_and_log("#{$sudo} chown #{user}:#{group} -R #{dirname}")

	puts "#{uuid}"
	exit 0
else
	exit 1	
end